### ISSUE TITLE
Error Details.

### ISSUE THREAD

**Issue by AlphaRandy** [Xyfir/accownt#7]
Build version: 27.0 
Current date: 2023-08-20 06:35:30 
Device: Motorola edge 5G UW (2021) 
OS version: Android 12 (SDK 31) 
 
Stack trace:  
java.lang.RuntimeException: Unable to start activity ComponentInfo{info.camposha.androidstudio/info.camposha.androidstudio.view.activities.LessonActivity}: java.lang.IndexOutOfBoundsException: Empty list doesn't contain element at index 0.
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3761)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3929)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2321)
	at android.os.Handler.dispatchMessage(Handler.java:111)
	at android.os.Looper.loopOnce(Looper.java:238)
	at android.os.Looper.loop(Looper.java:357)
	at android.app.ActivityThread.main(ActivityThread.java:8099)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1026)
Caused by: java.lang.IndexOutOfBoundsException: Empty list doesn't contain element at index 0.
	at ub.j.get(:1)
	at info.camposha.androidstudio.view.activities.LessonActivity.onCreate(:3)
	at android.app.Activity.performCreate(Activity.java:8232)
	at android.app.Activity.performCreate(Activity.java:8212)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1331)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3734)
	... 12 more

**Comment by MrXyfir** [comment]
I'm not sure what exactly the context of this is but it seems like a Java / Android issue that doesn't have anything to do with Accownt as far as I can tell. Accownt is intended to run on Node.js, which itself runs generally on Linux, Mac, or Windows. Android might be a bit tricky.
